### ISSUE TITLE
feat: add Scrum Board `.tsx` component

### ISSUE THREAD

**Issue by anicmarko9** [anicmarko9/scrum-board#46]
![image](https://github.com/anicmarko9/scrum-board/assets/73799942/54264000-a551-4e24-8d38-e4549bf4265c)

This image is simplified UI look. Make `.tsx` element like on this image, but don't worry about CSS.

Just make `.tsx` component, don't worry about Routing and all that. Just consider the side-menu alongside this new `.tsx` component:
```tsx
<main>
  <SideMenu />
  <Board />
</main>
```

**Comment by trba1810** [comment]
I'm working on this
